apiVersion: v1
kind: Secret
metadata:
  name: data-semantic-secret
  labels:
    app: data-semantic
type: Opaque
stringData:
  # 数据库敏感信息
  DB_PASSWORD: "123456"
  
  # 认证密钥
  ACCESS_SECRET: "a5b988283f7242dced46c769e4dcf9758140c484d8aa6b8e79e1ec06e22a9363"
  
  # Redis 密码 (如果使用)
  REDIS_PASSWORD: ""
