apiVersion: v1
kind: Service
metadata:
  name: data-semantic-api
  labels:
    app: data-semantic
    component: api
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    app: data-semantic
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: data-semantic-api-nodeport
  labels:
    app: data-semantic
    component: api
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30888
      protocol: TCP
      name: http
  selector:
    app: data-semantic
    component: api
